#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

#
# Publish this gear's Akka IP address and port.
#
printf "akka.tcp://${AKKA_ACTOR_SYSTEM_NAME}@${OPENSHIFT_GEAR_DNS}:${OPENSHIFT_PLAY2_AKKA_CLUSTER_PROXY_PORT}"