#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

#
# Publish this gear's Akka IP address and port.
#
echo "${OPENSHIFT_PLAY2_IP}:${OPENSHIFT_PLAY2_AKKA_CLUSTER_PROXY_PORT}"