#!/usr/bin/ruby

puts "Args are #{ARGV}"

gear_name = ARGV.shift
domain = ARGV.shift
gear_uuid = ARGV.shift

pub_outputs = []
while pub_output = ARGV.shift 
  pub_outputs << pub_output
end

pub_outputs.each_with_index do |pub_output, seed_index|
  gear_id, value = pub_output.split('=')
  puts "Setting AKKA_SEED_#{seed_index} to #{value}"
  File.open(ENV['OPENSHIFT_PLAY2_DIR'] + "env/AKKA_SEED_#{seed_index}", 'w'){ |env_file| env_file.puts value}
end